### ISSUE TITLE
declare: -A: invalid option on MacOS

### ISSUE THREAD

**Issue by z3cko** [wadiim/greek#1]
Just to let you know: this does not work on MacOS Ventura.
Here is the output on Mac OSX

```
./greek.sh: line 3: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
./greek.sh: line 34: conditional binary operator expected
./greek.sh: line 34: syntax error near `"$NAME_TO_LETTER[$n]"'
./greek.sh: line 34: `		if [[ -v "$NAME_TO_LETTER[$n]" ]]; then'
```

**Comment by wadiim** [comment]
Which version of Bash are you using? `declare -A` is used to declare associative arrays, which were introduced in bash-4.0-alpha. I got the same error on Mac OSX, with bash version 3.2.57(1)-release installed.
